---

- name: Clean tmp folder
  ignore_errors: yes
  command:  rm -rf "{{ playbook_dir }}/tmp"
  tags: [virtualbox]

- name: Remove old ansible inventory file
  file:
    path: "{{ playbook_dir }}/inventory/hosts"
    state: absent
  tags: [common]

- name: Copy new ansible inventory file
  copy:
    src: "{{ playbook_dir }}/templates/hosts.template"
    dest: "{{ playbook_dir }}/inventory/hosts"
  tags: [common]

- name: Remove all cluster token files 1
  ignore_errors: yes
  file:
    path: "{{ playbook_dir }}/vars/swarm-m-join-command"
    state: absent
  tags: [common]

- name: Remove all cluster token files 2
  ignore_errors: yes
  file:
    path: "{{ playbook_dir }}/vars/swarm-w-join-command"
    state: absent
  tags: [common]

- name: Remove all cluster token files 3
  ignore_errors: yes
  file:
    path: "{{ playbook_dir }}/vars/k8-m-join-command"
    state: absent
  tags: [common]

- name: Remove all cluster token files 4
  ignore_errors: yes
  file:
    path: "{{ playbook_dir }}/vars/k8-w-join-command"
    state: absent
  tags: [common]


- name: Remove old host file
  file:
    path: "{{ playbook_dir }}/inventory/hosts"
    state: absent
  tags: [common]

- name: Copy new host file
  copy:
    src: "{{ playbook_dir }}/templates/hosts.template"
    dest: "{{ playbook_dir }}/inventory/hosts"
  tags: [common]

- name: Set access right to SSH keys
  shell: "chmod 600 {{ playbook_dir }}/vars/*_key.pem"
  tags: [common]

- name: Delete files admin.conf
  file:
    path: "{{ playbook_dir }}/vars/admin.conf"
    state: absent
  tags: [common]

- name: Delete files k8-join-command
  file:
    path: "{{ playbook_dir }}/vars/k8-join-command"
    state: absent
  tags: [common]


- name: Add config 1 on 2 (virtualbox)
  lineinfile:
    dest: "{{ playbook_dir }}/inventory/hosts"
    insertafter: "# config"
    line: "ansible_ssh_private_key_file = ~/.ssh/id_rsa"
  tags: [virtualbox]

- name: Add config 2 on 2 (virtualbox)
  lineinfile:
    dest: "{{ playbook_dir }}/inventory/hosts"
    insertafter: "# config"
    line: "ansible_ssh_user=ansible"
  tags: [virtualbox]


- name: Add config 1 on 2 (aws)
  lineinfile:
    dest: "{{ playbook_dir }}/inventory/hosts"
    insertafter: "# config"
    line: "ansible_ssh_private_key_file={{ playbook_dir }}/vars/{{ aws_key_name }}.pem"
  tags: [aws]

- name: Add config 2 on 2 (aws,centos)
  lineinfile:
    dest: "{{ playbook_dir }}/inventory/hosts"
    insertafter: "# config"
    line: "ansible_ssh_user=centos"
  tags: [aws,centos]


- name: Add config 2 on 2 (aws,amzn2)
  lineinfile:
    dest: "{{ playbook_dir }}/inventory/hosts"
    insertafter: "# config"
    line: "ansible_ssh_user=ec2-user"
  tags: [aws,amzn2]
