---
#
# Fill ansible inventory file for VirtualBox VM provider
#
- name: sleep for 80 seconds to let vm to start and continue with playbook
  wait_for:
    timeout: 80
  tags: [virtualbox]

- name: Clean files
  ignore_errors: yes
  command: "rm {{ playbook_dir }}/vars/virtualbox_vmlist.txt"
  tags: [virtualbox]

- name: Create vm list files
  command: "touch {{ playbook_dir }}/vars/virtualbox_vmlist.txt"
  tags: [virtualbox]

- name: Fill in vm list files
  lineinfile:
    dest: "{{ playbook_dir }}/vars/virtualbox_vmlist.txt"
    line: "{{ item }}"
  with_lines: VBoxManage list vms
  tags: [virtualbox]

- name: Remove quote in vm list files
  replace:
    path: "{{ playbook_dir }}/vars/virtualbox_vmlist.txt"
    regexp: '\"'
    replace: ''

- name: Loop vm list files
  include_role:
    name: virtualbox_set_host_ansible_file_for_vm
  vars:
    myvmtoken: "{{ item.split(' ')[0] }}"
  with_lines: cat {{ playbook_dir }}/vars/virtualbox_vmlist.txt
  tags: [virtualbox]

- name: Clean files
  ignore_errors: yes
  command: "rm {{ playbook_dir }}/vars/virtualbox_vmlist.txt"
  tags: [virtualbox]
