---


- name: Clean tmp folder
  ignore_errors: yes
  command:  rm -rf "{{ playbook_dir }}/tmp"
  tags: [virtualbox]

- name: Remove old ansible inventory file
  file:
    path: "{{ playbook_dir }}/inventory/hosts"
    state: absent
  tags: [common]

- name: Copy new ansible inventory file
  copy:
    src: "{{ playbook_dir }}/templates/hosts.template"
    dest: "{{ playbook_dir }}/inventory/hosts"
  tags: [common]

- name: Remove all cluster token files 1
  ignore_errors: yes
  file:
    path: "{{ playbook_dir }}/vars/swarm-m-join-command"
    state: absent
  tags: [common]

- name: Remove all cluster token files 2
  ignore_errors: yes
  file:
    path: "{{ playbook_dir }}/vars/swarm-w-join-command"
    state: absent
  tags: [common]

- name: Remove all cluster token files 3
  ignore_errors: yes
  file:
    path: "{{ playbook_dir }}/vars/k8-m-join-command"
    state: absent
  tags: [common]

- name: Remove all cluster token files 4
  ignore_errors: yes
  file:
    path: "{{ playbook_dir }}/vars/k8-w-join-command"
    state: absent
  tags: [common]
