---
- name: Create glusterfs mount volume
  become: true
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/private/gfsbrick/gfsvol01'
  tags: [common]
# sudo mkdir -p /private/gfsbrick/gfsvol01
