---
# swarm  master

- name: Add FW rules for swarm / master 1
  become: true
  firewalld:
    port: 2376/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: [swarm]
# firewall-cmd --add-port=2376/tcp --permanent

- name: Add FW rules for swarm / master 2
  become: true
  firewalld:
    port: 2377/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: [swarm]
# sudo firewall-cmd --add-port=2377/tcp --permanent

- name: Add FW rules for swarm / master 3
  become: true
  firewalld:
    port: 7946/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: [swarm]
# sudo firewall-cmd --add-port=7946/tcp --permanent

- name: Add FW rules for swarm / master 4
  become: true
  firewalld:
    port: 7946/udp
    permanent: yes
    immediate: yes
    state: enabled
  tags: [swarm]
# sudo firewall-cmd --add-port=7946/udp --permanent

- name: Add FW rules for swarm / master 5
  become: true
  firewalld:
    port: 4789/udp
    permanent: yes
    immediate: yes
    state: enabled
  tags: [swarm]
# sudo firewall-cmd --add-port=4789/udp --permanent
