---
- name: Add Docker repository
  become: true
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  tags: [centos]

- name: Install Docker (centos)
  become: true
  command: dnf install docker-ce --nobest -y
  tags: [centos]

- name: Install Docker (amz2)
  become: true
  command: sudo amazon-linux-extras install -y docker
  tags: [amzn2]

- name: Install curl (centos)
  become: true
  yum:
    name: curl
    state: present
  tags: [centos]

- name: Install curl (amz2)
  become: true
  yum:
    name: curl
    state: present
  tags: [amzn2]

- name: Get last version number of Docker-compose
  command: "curl -s https://api.github.com/repos/docker/compose/releases/latest"
  register: curl_results
  tags: [common]

- name: Print last version number of Docker-compose
  set_fact:
    COMPOSE_VERSION: "{{ curl_results.stdout | regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: '.*tag_name.*:\s\"(.*)\",.*'
  tags: [common]

- name: Print last version number of Docker-compose
  debug:
    var: COMPOSE_VERSION
  tags: [common]

- name: Rmemove old Docker-compose version file
  become: true
  command: rm -f /usr/local/bin/docker-compose
  tags: [common]

- name: Get last Docker-compose version file
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ COMPOSE_VERSION }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
  tags: [common]

- name: Make last Docker-compose version executable
  become: true
  shell: chmod +x /usr/local/bin/docker-compose
  tags: [common]

- name: enable sysv dockerd service
  become: true
  service:
      name: docker.service
      enabled: yes
  tags: [common]

- name: Start service
  become: true
  service:
      name: docker.service
      state: started
  tags: [common]
