---
- name: Clean files
  ignore_errors: yes
  command: "rm {{ playbook_dir }}/vars/virtualbox_hddlist.txt"
  tags: [virtualbox]

- name: Create hdd list files
  command: "touch {{ playbook_dir }}/vars/virtualbox_hddlist.txt"
  tags: [virtualbox]

- name: Fill in hdd list files
  lineinfile:
    dest: "{{ playbook_dir }}/vars/virtualbox_hddlist.txt"
    line: "{{ item }}"
  with_lines: vboxmanage list hdds | sed -e '/./{H;$!d;}' -e 'x;/'"{{ myvmtoken }}"'/!d;' | grep UUID | egrep -v Parent| awk '{print $2}'
  tags: [virtualbox]

- name: Remove quote in hdd list files
  replace:
    path: "{{ playbook_dir }}/vars/virtualbox_vmlist.txt"
    regexp: '\"'
    replace: ''
  tags: [virtualbox]

- name: Stop VM
  ignore_errors: yes
  command: "vboxmanage controlvm {{ myvmtoken }} poweroff"
  tags: [virtualbox]

- name: sleep for 2 seconds to let vm to stop and continue with playbook
  wait_for:
    timeout: 2
  tags: [virtualbox]

- name: Discard VM
  ignore_errors: yes
  command: "VBoxManage discardstate {{ myvmtoken }}"
  tags: [virtualbox]

- name: sleep for 2 seconds to let vm to Discard and continue with playbook
  wait_for:
    timeout: 2
  tags: [virtualbox]

- name: Delete VM
  ignore_errors: yes
  command: "vboxmanage unregistervm {{ myvmtoken }} --delete"
  tags: [virtualbox]

- name: sleep for 2 seconds to let vm to Delete and continue with playbook
  wait_for:
    timeout: 2
  tags: [virtualbox]

- name: Loop hdd list files
  ignore_errors: yes
  command: "vboxmanage closemedium disk {{ hdd_item }} --delete"
  with_lines: cat {{ playbook_dir }}/vars/virtualbox_hddlist.txt
  loop_control:
    loop_var: hdd_item
  tags: [virtualbox]

- name: Clean hdd file list
  ignore_errors: yes
  command: "rm {{ playbook_dir }}/vars/virtualbox_hddlist.txt"
  tags: [virtualbox]
