---

# ssh

- name: Add firewall rules for glusterfs = Gluster Daemon
  become: true
  command: firewall-cmd --permanent --add-service=ssh
  tags: [common]


- name: Remove firewall rules for cockpit
  become: true
  command: firewall-cmd --remove-service=cockpit --permanent
  tags: [common]
