---

# ssh

- name: Add firewall rules for glusterfs = Gluster Daemon
  become: true
  firewalld:
    service: ssh
    permanent: yes
    immediate: yes
    state: enabled
  tags: [common]
# sudo firewall-cmd --permanent --add-service=ssh

- name: Remove firewall rules for cockpit
  become: true
  firewalld:
    service: cockpit
    permanent: yes
    immediate: yes
    state: disabled
  tags: [common]
# firewall-cmd --remove-service=cockpit --permanent
