cluster_vm_name_prefix: "c1"
vm_master_instance_count: 1
vm_worker_instance_count: 2
os_volume_size: 8
gluster_volume_size: 1
instance_group_letter: "A"
glusterfs_version: "7.5-1.el7"
docker_version: "19.03.11-3.el7"
docker_compose_version: "1.26.0"
k8_version: "1.18.3-0"

# to get latest available version
# sudo yum --showduplicates list docker-ce
# sudo yum --showduplicates list kubelet
# sudo yum --showduplicates list gluster
# curl -s https://api.github.com/repos/docker/compose/releases/latest  -> look at "tag_name" value
